// <auto-generated />
using System;
using Domovoy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domovoy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220717084553_Services")]
    partial class Services
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("ApartmentApplicationUser", b =>
                {
                    b.Property<int>("ApartmentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApartmentsId", "TenantsId");

                    b.HasIndex("TenantsId");

                    b.ToTable("ApartmentApplicationUser");
                });

            modelBuilder.Entity("ApartmentApplicationUser1", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantsWhoAddThisToCartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartId", "TenantsWhoAddThisToCartId");

                    b.HasIndex("TenantsWhoAddThisToCartId");

                    b.ToTable("ApartmentApplicationUser1");
                });

            modelBuilder.Entity("ApplicationUserChat", b =>
                {
                    b.Property<int>("ChatsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationUserChat");
                });

            modelBuilder.Entity("Domovoy.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Area")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaWithoutBalconies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseEntranceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivingArea")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseEntranceId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("Domovoy.Models.ApartmentHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApartmentServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InformerServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentialComplexId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentServiceId");

                    b.HasIndex("InformerServiceId");

                    b.HasIndex("ResidentialComplexId");

                    b.ToTable("ApartmentHouses");
                });

            modelBuilder.Entity("Domovoy.Models.ApartmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalContacts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequesterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("RequesterId");

                    b.ToTable("ApartmentRequests");
                });

            modelBuilder.Entity("Domovoy.Models.ApartmentService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SerivceProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("SerivceProviderId");

                    b.ToTable("ApartmentServices");
                });

            modelBuilder.Entity("Domovoy.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConstructionCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MainApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionCompanyId");

                    b.HasIndex("MainApartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domovoy.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApartmentHouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("ApartmentHouseId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Domovoy.Models.ConstructionCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConstructionCompanies");
                });

            modelBuilder.Entity("Domovoy.Models.HouseEntrance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentHouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnranceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentHouseId");

                    b.ToTable("HouseEntrances");
                });

            modelBuilder.Entity("Domovoy.Models.InformerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SerivceProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("SerivceProviderId");

                    b.ToTable("InformerServices");
                });

            modelBuilder.Entity("Domovoy.Models.InviteCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("Domovoy.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Domovoy.Models.ResidentialComplex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConstructionCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionCompanyId");

                    b.ToTable("ResidentialComplexes");
                });

            modelBuilder.Entity("Domovoy.Models.ServiceEntry<Domovoy.Models.ApartmentService>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Compleated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("ApartmentServiceEntries");
                });

            modelBuilder.Entity("Domovoy.Models.ServiceEntry<Domovoy.Models.InformerService>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Compleated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("InformerServiceEntries");
                });

            modelBuilder.Entity("Domovoy.Models.ServiceEntry<Domovoy.Models.UserService>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Compleated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserServiceEntries");
                });

            modelBuilder.Entity("Domovoy.Models.SmartHomeDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmartHomeDeviceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("SmartHomeDevices");
                });

            modelBuilder.Entity("Domovoy.Models.SmartHomeDeviceActionLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Perfomed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmartHomeDeviceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SmartHomeDeviceId");

                    b.ToTable("SmartHomeDeviceActionLog");
                });

            modelBuilder.Entity("Domovoy.Models.UserService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SerivceProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UserMustHaveAnApartment")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SerivceProviderId");

                    b.ToTable("UserServices");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApartmentApplicationUser", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", null)
                        .WithMany()
                        .HasForeignKey("ApartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TenantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApartmentApplicationUser1", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", null)
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TenantsWhoAddThisToCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationUserChat", b =>
                {
                    b.HasOne("Domovoy.Models.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domovoy.Models.Apartment", b =>
                {
                    b.HasOne("Domovoy.Models.HouseEntrance", "HouseEntrance")
                        .WithMany("Apartments")
                        .HasForeignKey("HouseEntranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", "Owner")
                        .WithMany("OwndedApartments")
                        .HasForeignKey("OwnerId");

                    b.Navigation("HouseEntrance");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domovoy.Models.ApartmentHouse", b =>
                {
                    b.HasOne("Domovoy.Models.ApartmentService", null)
                        .WithMany("ScopeHouses")
                        .HasForeignKey("ApartmentServiceId");

                    b.HasOne("Domovoy.Models.InformerService", null)
                        .WithMany("ScopeHouses")
                        .HasForeignKey("InformerServiceId");

                    b.HasOne("Domovoy.Models.ResidentialComplex", "ResidentialComplex")
                        .WithMany("ApartmentHouses")
                        .HasForeignKey("ResidentialComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentialComplex");
                });

            modelBuilder.Entity("Domovoy.Models.ApartmentRequest", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", "Apartment")
                        .WithMany("ApartmentRequests")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", "Requester")
                        .WithMany("ApartmentRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Domovoy.Models.ApartmentService", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", null)
                        .WithMany("ApartmentServices")
                        .HasForeignKey("ApartmentId");

                    b.HasOne("Domovoy.Models.ApplicationUser", "SerivceProvider")
                        .WithMany("ApartmentServicesPrivided")
                        .HasForeignKey("SerivceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerivceProvider");
                });

            modelBuilder.Entity("Domovoy.Models.ApplicationUser", b =>
                {
                    b.HasOne("Domovoy.Models.ConstructionCompany", "ConstructionCompany")
                        .WithMany("Employees")
                        .HasForeignKey("ConstructionCompanyId");

                    b.HasOne("Domovoy.Models.Apartment", "MainApartment")
                        .WithMany("TenantsWhoMainThis")
                        .HasForeignKey("MainApartmentId");

                    b.Navigation("ConstructionCompany");

                    b.Navigation("MainApartment");
                });

            modelBuilder.Entity("Domovoy.Models.Chat", b =>
                {
                    b.HasOne("Domovoy.Models.ApplicationUser", "Administrator")
                        .WithMany("AdminChats")
                        .HasForeignKey("AdministratorId");

                    b.HasOne("Domovoy.Models.ApartmentHouse", "ApartmentHouse")
                        .WithMany()
                        .HasForeignKey("ApartmentHouseId");

                    b.Navigation("Administrator");

                    b.Navigation("ApartmentHouse");
                });

            modelBuilder.Entity("Domovoy.Models.HouseEntrance", b =>
                {
                    b.HasOne("Domovoy.Models.ApartmentHouse", "ApartmentHouse")
                        .WithMany("HouseEntrances")
                        .HasForeignKey("ApartmentHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentHouse");
                });

            modelBuilder.Entity("Domovoy.Models.InformerService", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", null)
                        .WithMany("InformerServices")
                        .HasForeignKey("ApartmentId");

                    b.HasOne("Domovoy.Models.ApplicationUser", "SerivceProvider")
                        .WithMany("InformerServicesPrivided")
                        .HasForeignKey("SerivceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerivceProvider");
                });

            modelBuilder.Entity("Domovoy.Models.InviteCode", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", "Apartment")
                        .WithMany("InviteCodes")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Domovoy.Models.Message", b =>
                {
                    b.HasOne("Domovoy.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Domovoy.Models.ResidentialComplex", b =>
                {
                    b.HasOne("Domovoy.Models.ConstructionCompany", "ConstructionCompany")
                        .WithMany("ResidentialComplexes")
                        .HasForeignKey("ConstructionCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructionCompany");
                });

            modelBuilder.Entity("Domovoy.Models.ServiceEntry<Domovoy.Models.ApartmentService>", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId");

                    b.HasOne("Domovoy.Models.ApartmentService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Apartment");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domovoy.Models.ServiceEntry<Domovoy.Models.InformerService>", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId");

                    b.HasOne("Domovoy.Models.InformerService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Apartment");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domovoy.Models.ServiceEntry<Domovoy.Models.UserService>", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId");

                    b.HasOne("Domovoy.Models.UserService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Apartment");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domovoy.Models.SmartHomeDevice", b =>
                {
                    b.HasOne("Domovoy.Models.Apartment", "Apartment")
                        .WithMany("SmartHomeDevices")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("Domovoy.Models.SmartHomeDeviceActionLogEntry", b =>
                {
                    b.HasOne("Domovoy.Models.SmartHomeDevice", "SmartHomeDevice")
                        .WithMany("ActionLogEntries")
                        .HasForeignKey("SmartHomeDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartHomeDevice");
                });

            modelBuilder.Entity("Domovoy.Models.UserService", b =>
                {
                    b.HasOne("Domovoy.Models.ApplicationUser", "SerivceProvider")
                        .WithMany("UserServicesPrivided")
                        .HasForeignKey("SerivceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerivceProvider");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Domovoy.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Domovoy.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domovoy.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Domovoy.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domovoy.Models.Apartment", b =>
                {
                    b.Navigation("ApartmentRequests");

                    b.Navigation("ApartmentServices");

                    b.Navigation("InformerServices");

                    b.Navigation("InviteCodes");

                    b.Navigation("SmartHomeDevices");

                    b.Navigation("TenantsWhoMainThis");
                });

            modelBuilder.Entity("Domovoy.Models.ApartmentHouse", b =>
                {
                    b.Navigation("HouseEntrances");
                });

            modelBuilder.Entity("Domovoy.Models.ApartmentService", b =>
                {
                    b.Navigation("ScopeHouses");
                });

            modelBuilder.Entity("Domovoy.Models.ApplicationUser", b =>
                {
                    b.Navigation("AdminChats");

                    b.Navigation("ApartmentRequests");

                    b.Navigation("ApartmentServicesPrivided");

                    b.Navigation("InformerServicesPrivided");

                    b.Navigation("OwndedApartments");

                    b.Navigation("UserServicesPrivided");
                });

            modelBuilder.Entity("Domovoy.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domovoy.Models.ConstructionCompany", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("ResidentialComplexes");
                });

            modelBuilder.Entity("Domovoy.Models.HouseEntrance", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("Domovoy.Models.InformerService", b =>
                {
                    b.Navigation("ScopeHouses");
                });

            modelBuilder.Entity("Domovoy.Models.ResidentialComplex", b =>
                {
                    b.Navigation("ApartmentHouses");
                });

            modelBuilder.Entity("Domovoy.Models.SmartHomeDevice", b =>
                {
                    b.Navigation("ActionLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
